#############################################################################
# Generated by PAGE version 5.3
#  in conjunction with Tcl version 8.6
#  Jul 21, 2020 05:03:32 PM CDT  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}



    menu .pop62 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font {{Segoe UI} 9} \
        -foreground black -tearoff 1 
    vTcl:DefineAlias ".pop62" "Popupmenu1" vTcl:WidgetProc "" 1

proc vTclWindow.top43 {base} {
    global vTcl
    if {$base == ""} {
        set base .top43
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m59" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 120x30+740+194
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm grid $top 10 3 8 17
    wm maxsize $top 4484 1401
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "MainWindow" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    canvas $top.can46 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -closeenough 1.0 \
        -height 153 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -insertbackground black -relief ridge \
        -selectbackground #c4c4c4 -selectforeground black -width 125 
    vTcl:DefineAlias "$top.can46" "PhotoBox" vTcl:WidgetProc "MainWindow" 1
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $top.scr51 \
        -background $vTcl(actual_gui_bg) -height 75 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 125 
    vTcl:DefineAlias "$top.scr51" "MainDBLB" vTcl:WidgetProc "MainWindow" 1
    bind $top.scr51 <<ListboxSelect>> {
        lambda e: mainDBSelected(e)
    }

    $top.scr51.01 configure -background white \
        -cursor xterm \
        -disabledforeground #a3a3a3 \
        -font TkFixedFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -selectmode single \
        -width 10 \
        -listvariable Empty
    label $top.lab54 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text namePlaceHolder 
    vTcl:DefineAlias "$top.lab54" "PlayerName" vTcl:WidgetProc "MainWindow" 1
    set site_3_0 $top.m59
    menu $site_3_0 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    $site_3_0 add cascade \
        -menu "$site_3_0.men61" -activebackground $vTcl(analog_color_m) \
        -activeforeground #000000 -background $vTcl(pr,menubgcolor) \
        -command {{}} -font TkMenuFont -foreground $vTcl(pr,menufgcolor) \
        -label File 
    menu $site_3_0.men61 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font {{Segoe UI} 9} \
        -foreground black -tearoff 0 
    $site_3_0.men61 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command {{}} -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -label Quit 
    $site_3_0 add cascade \
        -menu "$site_3_0.men61" -activebackground $vTcl(analog_color_m) \
        -activeforeground #000000 -background $vTcl(pr,menubgcolor) \
        -command {{}} -font TkMenuFont -foreground $vTcl(pr,menufgcolor) \
        -label File -menu "$site_3_0.men63" \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command {{}} -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -label Database 
    menu $site_3_0.men63 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font {{Segoe UI} 9} \
        -foreground black -tearoff 0 
    $site_3_0.men63 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command {{}} -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -label {Clear Database} 
    $site_3_0.men63 add separator \
        -background $vTcl(pr,menubgcolor) 
    $site_3_0.men63 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command {{}} -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -label {Import from CSV} 
    $site_3_0.men63 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command {{}} -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -label {Export from CSV} 
    label $top.lab64 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Current Database} 
    vTcl:DefineAlias "$top.lab64" "DBLabel" vTcl:WidgetProc "MainWindow" 1
    label $top.lab64.lab51 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text count 
    vTcl:DefineAlias "$top.lab64.lab51" "countVAR" vTcl:WidgetProc "MainWindow" 1
    label $top.lab64.lab44 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text Count 
    vTcl:DefineAlias "$top.lab64.lab44" "count" vTcl:WidgetProc "MainWindow" 1
    ttk::style configure TNotebook -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -foreground $vTcl(actual_gui_fg)
    ttk::style configure TNotebook.Tab -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style map TNotebook.Tab -background [list disabled $vTcl(actual_gui_bg) selected $vTcl(pr,guicomplement_color)]
    ttk::notebook $top.tNo66 \
        -width 353 -height 92 -takefocus {} 
    vTcl:DefineAlias "$top.tNo66" "AddSelector" vTcl:WidgetProc "MainWindow" 1
    frame $top.tNo66.t0 \
        -borderwidth 1 -relief sunken -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo66.t0" "AddSelector_t1_1" vTcl:WidgetProc "MainWindow" 1
    $top.tNo66 add $top.tNo66.t0 \
        -padding 0 -sticky nsew -state normal -text {Add Player} -image {} \
        -compound left -underline -1 
    set site_4_0  $top.tNo66.t0
    label $site_4_0.lab78 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Player Name:} 
    vTcl:DefineAlias "$site_4_0.lab78" "addPlayerNameLab" vTcl:WidgetProc "MainWindow" 1
    entry $site_4_0.ent79 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 124 
    vTcl:DefineAlias "$site_4_0.ent79" "playerNameEntry" vTcl:WidgetProc "MainWindow" 1
    bind $site_4_0.ent79 <Enter> {
        lambda e: xxx(e)
    }
    label $site_4_0.lab81 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Position (Op):} 
    vTcl:DefineAlias "$site_4_0.lab81" "addPlayerPosLab" vTcl:WidgetProc "MainWindow" 1
    ttk::combobox $site_4_0.tCo82 \
        \
        -values {QB RB FB WR TE T G C DE DT ROLB LOLB OLB ILB CB SS FS S P K LS} \
        -font TkTextFont -textvariable addPPosSearchCB -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$site_4_0.tCo82" "playerPositionCB" vTcl:WidgetProc "MainWindow" 1
    bind $site_4_0.tCo82 <FocusOut> {
        lambda e: playerSearchPosFocusOUT(e)
    }
    button $site_4_0.but83 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Search 
    vTcl:DefineAlias "$site_4_0.but83" "playerSearchBTN" vTcl:WidgetProc "MainWindow" 1
    bind $site_4_0.but83 <Button-1> {
        lambda e: playerSearchBTNPress(e)
    }
    place $site_4_0.lab78 \
        -in $site_4_0 -x 0 -relx 0.018 -y 0 -rely 0.167 -width 0 \
        -relwidth 0.245 -height 0 -relheight 0.303 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent79 \
        -in $site_4_0 -x 0 -relx 0.265 -y 0 -rely 0.182 -width 124 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab81 \
        -in $site_4_0 -x 0 -relx 0.029 -y 0 -rely 0.603 -width 0 \
        -relwidth 0.223 -height 0 -relheight 0.317 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tCo82 \
        -in $site_4_0 -x 0 -relx 0.264 -y 0 -rely 0.524 -width 0 \
        -relwidth 0.186 -height 0 -relheight 0.46 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but83 \
        -in $site_4_0 -x 0 -relx 0.796 -y 0 -rely 0.333 -width 46 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    frame $top.tNo66.t1 \
        -borderwidth 1 -relief sunken -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo66.t1" "AddSelector_t2_2" vTcl:WidgetProc "MainWindow" 1
    $top.tNo66 add $top.tNo66.t1 \
        -padding 0 -sticky nsew -state normal -text {Add Team} -image {} \
        -compound left -underline -1 
    set site_4_1  $top.tNo66.t1
    label $site_4_1.lab84 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Team: 
    vTcl:DefineAlias "$site_4_1.lab84" "addTeamTeamLab" vTcl:WidgetProc "MainWindow" 1
    label $site_4_1.lab85 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Year: 
    vTcl:DefineAlias "$site_4_1.lab85" "addTeamYearLab" vTcl:WidgetProc "MainWindow" 1
    ttk::combobox $site_4_1.tCo87 \
        \
        -values {49ERS BEARS BENGALS BILLS BRONCOS BROWNS BUCCANEERS CARDINALS CHARGERS CHIEFS COLTS COWBOYS DOLPHINS EAGLES FALCONS GIANTS JAGUARS JETS LIONS PACKERS PANTHERS PATRIOTS RAIDERS RAMS RAVENS REDSKINS SAINTS SEAHAWKS STEELERS TEXANS TITANS VIKINGS} \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_4_1.tCo87" "teamSelectCB" vTcl:WidgetProc "MainWindow" 1
    bind $site_4_1.tCo87 <FocusOut> {
        lambda e: teamSearchTeamFocusOUT(e)
    }
    entry $site_4_1.ent88 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 84 
    vTcl:DefineAlias "$site_4_1.ent88" "teamYearEntry" vTcl:WidgetProc "MainWindow" 1
    bind $site_4_1.ent88 <FocusOut> {
        lambda e: teamSearchYearFocusOUT(e)
    }
    button $site_4_1.but89 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Search 
    vTcl:DefineAlias "$site_4_1.but89" "teamSearchBTN" vTcl:WidgetProc "MainWindow" 1
    bind $site_4_1.but89 <Button-1> {
        lambda e: teamSearchBTNPress(e)
    }
    place $site_4_1.lab84 \
        -in $site_4_1 -x 0 -relx 0.06 -y 0 -rely 0.19 -width 0 \
        -relwidth 0.112 -height 0 -relheight 0.302 -anchor nw \
        -bordermode ignore 
    place $site_4_1.lab85 \
        -in $site_4_1 -x 0 -relx 0.074 -y 0 -rely 0.635 -width 0 \
        -relwidth 0.095 -height 0 -relheight 0.302 -anchor nw \
        -bordermode ignore 
    place $site_4_1.tCo87 \
        -in $site_4_1 -x 0 -relx 0.178 -y 0 -rely 0.143 -width 0 \
        -relwidth 0.421 -height 0 -relheight 0.46 -anchor nw \
        -bordermode ignore 
    place $site_4_1.ent88 \
        -in $site_4_1 -x 0 -relx 0.175 -y 0 -rely 0.635 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.but89 \
        -in $site_4_1 -x 0 -relx 0.796 -y 0 -rely 0.333 -width 46 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    label $top.lab67 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Position: 
    vTcl:DefineAlias "$top.lab67" "PosLab" vTcl:WidgetProc "MainWindow" 1
    label $top.lab68 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Team: 
    vTcl:DefineAlias "$top.lab68" "teamLab" vTcl:WidgetProc "MainWindow" 1
    label $top.lab69 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Born: 
    vTcl:DefineAlias "$top.lab69" "bdayLab" vTcl:WidgetProc "MainWindow" 1
    label $top.lab70 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text H/W: 
    vTcl:DefineAlias "$top.lab70" "hwLab" vTcl:WidgetProc "MainWindow" 1
    label $top.lab71 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text College: 
    vTcl:DefineAlias "$top.lab71" "collegeLab" vTcl:WidgetProc "MainWindow" 1
    label $top.lab72 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text PlayerID: 
    vTcl:DefineAlias "$top.lab72" "pIdLab" vTcl:WidgetProc "MainWindow" 1
    canvas $top.can77 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -closeenough 1.0 \
        -height 103 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -insertbackground black -relief ridge \
        -selectbackground #c4c4c4 -selectforeground black -width 90 
    vTcl:DefineAlias "$top.can77" "AddCanvas" vTcl:WidgetProc "MainWindow" 1
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $top.scr90 \
        -background $vTcl(actual_gui_bg) -height 75 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 125 
    vTcl:DefineAlias "$top.scr90" "searchLB" vTcl:WidgetProc "MainWindow" 1
    bind $top.scr90 <<ListboxSelect>> {
        lambda e: searchLBSelected(e)
    }

    $top.scr90.01 configure -background white \
        -cursor X_cursor \
        -disabledforeground #a3a3a3 \
        -font TkFixedFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -selectmode single \
        -setgrid 1 \
        -width 10
    label $top.lab91 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Add to Database} 
    vTcl:DefineAlias "$top.lab91" "addToDBLAB" vTcl:WidgetProc "MainWindow" 1
    ttk::separator $top.tSe94
    vTcl:DefineAlias "$top.tSe94" "TSeparator1" vTcl:WidgetProc "MainWindow" 1
    ttk::separator $top.tSe95 \
        -orient vertical 
    vTcl:DefineAlias "$top.tSe95" "TSeparator2" vTcl:WidgetProc "MainWindow" 1
    ttk::separator $top.tSe53
    vTcl:DefineAlias "$top.tSe53" "TSeparator3" vTcl:WidgetProc "MainWindow" 1
    label $top.lab55 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text bdayPlaceHolder 
    vTcl:DefineAlias "$top.lab55" "bdayVALUE" vTcl:WidgetProc "MainWindow" 1
    label $top.lab56 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text hwPlaceHolder 
    vTcl:DefineAlias "$top.lab56" "hwVALUE" vTcl:WidgetProc "MainWindow" 1
    label $top.lab57 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text collegePlaceholder 
    vTcl:DefineAlias "$top.lab57" "collegeVALUE" vTcl:WidgetProc "MainWindow" 1
    label $top.lab58 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text posPlaceholder 
    vTcl:DefineAlias "$top.lab58" "posVALUE" vTcl:WidgetProc "MainWindow" 1
    label $top.lab59 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text teamPlaceholder 
    vTcl:DefineAlias "$top.lab59" "teamVALUE" vTcl:WidgetProc "MainWindow" 1
    label $top.lab60 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text playerIDPlaceholder 
    vTcl:DefineAlias "$top.lab60" "idVALUE" vTcl:WidgetProc "MainWindow" 1
    label $top.lab61 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text searchNamePH 
    vTcl:DefineAlias "$top.lab61" "searchNameVALUE" vTcl:WidgetProc "MainWindow" 1
    labelframe $top.lab63 \
        -font TkDefaultFont -foreground black -relief sunken -text Info \
        -background $vTcl(actual_gui_bg) -height 94 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 198 
    vTcl:DefineAlias "$top.lab63" "searchInfoBOX" vTcl:WidgetProc "MainWindow" 1
    set site_3_0 $top.lab63
    label $site_3_0.lab66 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text bdayPH 
    vTcl:DefineAlias "$site_3_0.lab66" "bdaySearchVALUE" vTcl:WidgetProc "MainWindow" 1
    label $site_3_0.lab75 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text collegePH 
    vTcl:DefineAlias "$site_3_0.lab75" "collegeSearchVALUE" vTcl:WidgetProc "MainWindow" 1
    label $site_3_0.lab76 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text teamPH 
    vTcl:DefineAlias "$site_3_0.lab76" "teamsearchVALUE" vTcl:WidgetProc "MainWindow" 1
    label $site_3_0.lab77 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text playerIDPH 
    vTcl:DefineAlias "$site_3_0.lab77" "pidsearchVALUE" vTcl:WidgetProc "MainWindow" 1
    place $site_3_0.lab66 \
        -in $site_3_0 -x 0 -relx 0.202 -y 0 -rely 0.106 -width 0 \
        -relwidth 0.576 -height 0 -relheight 0.223 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab75 \
        -in $site_3_0 -x 0 -relx 0.03 -y 0 -rely 0.319 -width 0 \
        -relwidth 0.929 -height 0 -relheight 0.223 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab76 \
        -in $site_3_0 -x 0 -relx 0.051 -y 0 -rely 0.532 -width 0 \
        -relwidth 0.879 -height 0 -relheight 0.223 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab77 \
        -in $site_3_0 -x 0 -relx 0.056 -y 0 -rely 0.745 -width 0 \
        -relwidth 0.879 -height 0 -relheight 0.223 -anchor nw \
        -bordermode ignore 
    button $top.but64 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Delete Entry} 
    vTcl:DefineAlias "$top.but64" "deleteBTN" vTcl:WidgetProc "MainWindow" 1
    bind $top.but64 <Button-1> {
        lambda e: deleteEntryPress(e)
    }
    label $top.lab65 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text { pos} 
    vTcl:DefineAlias "$top.lab65" "searchPosVALUE" vTcl:WidgetProc "MainWindow" 1
    label $top.lab73 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text hwSearchVALUE 
    vTcl:DefineAlias "$top.lab73" "Label1" vTcl:WidgetProc "MainWindow" 1
    label $top.lab78 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Filter 
    vTcl:DefineAlias "$top.lab78" "Label2" vTcl:WidgetProc "MainWindow" 1
    entry $top.ent80 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 234 
    vTcl:DefineAlias "$top.ent80" "pnameFILTER" vTcl:WidgetProc "MainWindow" 1
    bind $top.ent80 <FocusOut> {
        lambda e: filterNameFocusOUT(e)
    }
    label $top.lab81 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Player Name} 
    vTcl:DefineAlias "$top.lab81" "filterpname" vTcl:WidgetProc "MainWindow" 1
    ttk::combobox $top.tCo82 \
        \
        -values {QB RB FB WR TE T G C DE DT ROLB LOLB OLB ILB CB SS FS S P K LS} \
        -font TkTextFont -textvariable posFilterCB -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo82" "posFilterCB" vTcl:WidgetProc "MainWindow" 1
    bind $top.tCo82 <FocusOut> {
        lambda e: filterPosFocusOUT(e)
    }
    ttk::combobox $top.tCo83 \
        \
        -values {49ERS BEARS BENGALS BILLS BRONCOS BROWNS BUCCANEERS CARDINALS CHARGERS CHIEFS COLTS COWBOYS DOLPHINS EAGLES FALCONS GIANTS JAGUARS JETS LIONS PACKERS PANTHERS PATRIOTS RAIDERS RAMS RAVENS REDSKINS SAINTS SEAHAWKS STEELERS TEXANS TITANS VIKINGS} \
        -font TkTextFont -textvariable teamFilterCB -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo83" "teamCBFilter" vTcl:WidgetProc "MainWindow" 1
    bind $top.tCo83 <FocusOut> {
        lambda e: filterTeamFocusOUT(e)
    }
    label $top.lab86 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Position 
    vTcl:DefineAlias "$top.lab86" "Label3" vTcl:WidgetProc "MainWindow" 1
    label $top.lab87 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Team 
    vTcl:DefineAlias "$top.lab87" "Label4" vTcl:WidgetProc "MainWindow" 1
    ttk::combobox $top.tCo44 \
        \
        -values {{AFC North} {AFC East} {AFC West} {AFC South} {NFC North} {NFC East} {NFC West} {NFC South}} \
        -font TkTextFont -textvariable divFilterCB -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo44" "divisionCBFILTER" vTcl:WidgetProc "MainWindow" 1
    bind $top.tCo44 <FocusOut> {
        lambda e: filterDivFocusOUT(e)
    }
    label $top.lab45 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Division 
    vTcl:DefineAlias "$top.lab45" "divFilter" vTcl:WidgetProc "MainWindow" 1
    entry $top.ent46 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 94 
    vTcl:DefineAlias "$top.ent46" "yearENTRYFilter" vTcl:WidgetProc "MainWindow" 1
    bind $top.ent46 <FocusOut> {
        lambda e: filterYearFocusOUT(e)
    }
    label $top.lab48 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Year 
    vTcl:DefineAlias "$top.lab48" "yearFilter" vTcl:WidgetProc "MainWindow" 1
    button $top.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Filter to CSV} 
    vTcl:DefineAlias "$top.but49" "filtertoCSVBTN" vTcl:WidgetProc "MainWindow" 1
    bind $top.but49 <Button-1> {
        lambda e: filterToCsvBTNPress(e)
    }
    button $top.but50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Filter 
    vTcl:DefineAlias "$top.but50" "filterBTN" vTcl:WidgetProc "MainWindow" 1
    bind $top.but50 <Button-1> {
        lambda e: filterBTNPress(e)
    }
    button $top.but44 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Add 
    vTcl:DefineAlias "$top.but44" "addBTN" vTcl:WidgetProc "MainWindow" 1
    bind $top.but44 <Button-1> {
        lambda e: addPlayerToDB(e)
    }
    button $top.but45 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Add All} 
    vTcl:DefineAlias "$top.but45" "addAllBTN" vTcl:WidgetProc "MainWindow" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.can46 \
        -in $top -x 0 -relx 0.646 -y 0 -rely 0.066 -width 0 -relwidth 0.13 \
        -height 0 -relheight 0.251 -anchor nw -bordermode ignore 
    place $top.scr51 \
        -in $top -x 0 -relx 0.021 -y 0 -rely 0.068 -width 0 -relwidth 0.602 \
        -height 0 -relheight 0.424 -anchor nw -bordermode ignore 
    place $top.lab54 \
        -in $top -x 0 -relx 0.781 -y 0 -rely 0.063 -width 0 -relwidth 0.213 \
        -height 0 -relheight 0.032 -anchor nw -bordermode ignore 
    place $top.lab64 \
        -in $top -x 0 -relx 0.031 -y 0 -rely 0.016 -width 0 -relwidth 0.588 \
        -height 0 -relheight 0.033 -anchor nw -bordermode ignore 
    place $top.lab64.lab51 \
        -in $top.lab64 -x 0 -relx 0.833 -y 0 -rely -0.167 -width 0 \
        -relwidth 0.149 -height 0 -relheight 20 -anchor nw -bordermode ignore 
    place $top.lab64.lab44 \
        -in $top.lab64 -x 0 -relx 0.786 -y 0 -width 0 -relwidth 0.132 \
        -height 0 -relheight 1 -anchor nw -bordermode ignore 
    place $top.tNo66 \
        -in $top -x 0 -relx 0.021 -y 0 -rely 0.834 -width 0 -relwidth 0.368 \
        -height 0 -relheight 0.151 -anchor nw -bordermode ignore 
    place $top.lab67 \
        -in $top -x 0 -relx 0.781 -y 0 -rely 0.19 -width 0 -relwidth 0.051 \
        -height 0 -relheight 0.033 -anchor nw -bordermode ignore 
    place $top.lab68 \
        -in $top -x 0 -relx 0.792 -y 0 -rely 0.22 -width 0 -relwidth 0.046 \
        -height 0 -relheight 0.033 -anchor nw -bordermode ignore 
    place $top.lab69 \
        -in $top -x 0 -relx 0.796 -y 0 -rely 0.095 -width 0 -relwidth 0.035 \
        -height 0 -relheight 0.033 -anchor nw -bordermode ignore 
    place $top.lab70 \
        -in $top -x 0 -relx 0.799 -y 0 -rely 0.127 -width 0 -relwidth 0.029 \
        -height 0 -relheight 0.033 -anchor nw -bordermode ignore 
    place $top.lab71 \
        -in $top -x 0 -relx 0.781 -y 0 -rely 0.159 -width 0 -relwidth 0.05 \
        -height 0 -relheight 0.032 -anchor nw -bordermode ignore 
    place $top.lab72 \
        -in $top -x 0 -relx 0.779 -y 0 -rely 0.249 -width 0 -relwidth 0.056 \
        -height 0 -relheight 0.033 -anchor nw -bordermode ignore 
    place $top.can77 \
        -in $top -x 0 -relx 0.458 -y 0 -rely 0.571 -width 0 -relwidth 0.094 \
        -height 0 -relheight 0.162 -anchor nw -bordermode ignore 
    place $top.scr90 \
        -in $top -x 0 -relx 0.021 -y 0 -rely 0.574 -width 0 -relwidth 0.367 \
        -height 0 -relheight 0.246 -anchor nw -bordermode ignore 
    place $top.lab91 \
        -in $top -x 0 -relx 0.021 -y 0 -rely 0.524 -width 0 -relwidth 0.598 \
        -height 0 -relheight 0.033 -anchor nw -bordermode ignore 
    place $top.tSe94 \
        -in $top -x 0 -relx 0.021 -y 0 -rely 0.508 -width 0 -relwidth 0.604 \
        -height 0 -relheight 0.003 -anchor nw -bordermode inside 
    place $top.tSe95 \
        -in $top -x 0 -relx 0.625 -y 0 -rely 0.508 -height 0 -relheight 0.477 \
        -anchor nw -bordermode inside 
    place $top.tSe53 \
        -in $top -x 0 -relx 0.646 -y 0 -rely 0.38 -width 0 -relwidth 0.332 \
        -height 0 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab55 \
        -in $top -x 0 -relx 0.833 -y 0 -rely 0.095 -width 0 -relwidth 0.154 \
        -height 0 -relheight 0.033 -anchor nw -bordermode ignore 
    place $top.lab56 \
        -in $top -x 0 -relx 0.831 -y 0 -rely 0.128 -width 0 -relwidth 0.154 \
        -height 0 -relheight 0.034 -anchor nw -bordermode ignore 
    place $top.lab57 \
        -in $top -x 0 -relx 0.833 -y 0 -rely 0.159 -width 0 -relwidth 0.154 \
        -height 0 -relheight 0.034 -anchor nw -bordermode ignore 
    place $top.lab58 \
        -in $top -x 0 -relx 0.833 -y 0 -rely 0.19 -width 0 -relwidth 0.154 \
        -height 0 -relheight 0.033 -anchor nw -bordermode ignore 
    place $top.lab59 \
        -in $top -x 0 -relx 0.833 -y 0 -rely 0.22 -width 0 -relwidth 0.154 \
        -height 0 -relheight 0.034 -anchor nw -bordermode ignore 
    place $top.lab60 \
        -in $top -x 0 -relx 0.833 -y 0 -rely 0.248 -width 0 -relwidth 0.157 \
        -height 0 -relheight 0.034 -anchor nw -bordermode ignore 
    place $top.lab61 \
        -in $top -x 0 -relx 0.395 -y 0 -rely 0.738 -width 0 -relwidth 0.224 \
        -height 0 -relheight 0.034 -anchor nw -bordermode ignore 
    place $top.lab63 \
        -in $top -x 0 -relx 0.406 -y 0 -rely 0.77 -width 0 -relwidth 0.206 \
        -height 0 -relheight 0.154 -anchor nw -bordermode ignore 
    place $top.but64 \
        -in $top -x 0 -relx 0.802 -y 0 -rely 0.308 -width 157 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab65 \
        -in $top -x 0 -relx 0.552 -y 0 -rely 0.574 -width 0 -relwidth 0.067 \
        -height 0 -relheight 0.034 -anchor nw -bordermode ignore 
    place $top.lab73 \
        -in $top -x 0 -relx 0.552 -y 0 -rely 0.607 -width 0 -relwidth 0.067 \
        -height 0 -relheight 0.034 -anchor nw -bordermode ignore 
    place $top.lab78 \
        -in $top -x 0 -relx 0.627 -y 0 -rely 0.393 -width 0 -relwidth 0.37 \
        -height 0 -relheight 0.033 -anchor nw -bordermode ignore 
    place $top.ent80 \
        -in $top -x 0 -relx 0.688 -y 0 -rely 0.475 -width 234 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab81 \
        -in $top -x 0 -relx 0.688 -y 0 -rely 0.443 -width 0 -relwidth 0.245 \
        -height 0 -relheight 0.034 -anchor nw -bordermode ignore 
    place $top.tCo82 \
        -in $top -x 0 -relx 0.688 -y 0 -rely 0.558 -width 0 -relwidth 0.069 \
        -height 0 -relheight 0.051 -anchor nw -bordermode ignore 
    place $top.tCo83 \
        -in $top -x 0 -relx 0.781 -y 0 -rely 0.558 -width 0 -relwidth 0.149 \
        -height 0 -relheight 0.051 -anchor nw -bordermode ignore 
    place $top.lab86 \
        -in $top -x 0 -relx 0.685 -y 0 -rely 0.536 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.018 -anchor nw -bordermode ignore 
    place $top.lab87 \
        -in $top -x 0 -relx 0.78 -y 0 -rely 0.538 -width 0 -relwidth 0.15 \
        -height 0 -relheight 0.018 -anchor nw -bordermode ignore 
    place $top.tCo44 \
        -in $top -x 0 -relx 0.688 -y 0 -rely 0.636 -width 0 -relwidth 0.129 \
        -height 0 -relheight 0.037 -anchor nw -bordermode ignore 
    place $top.lab45 \
        -in $top -x 0 -relx 0.688 -y 0 -rely 0.615 -width 0 -relwidth 0.129 \
        -height 0 -relheight 0.019 -anchor nw -bordermode ignore 
    place $top.ent46 \
        -in $top -x 0 -relx 0.831 -y 0 -rely 0.637 -width 94 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 0 -relx 0.833 -y 0 -rely 0.617 -width 0 -relwidth 0.097 \
        -height 0 -relheight 0.019 -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 0 -relx 0.688 -y 0 -rely 0.712 -width 117 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but50 \
        -in $top -x 0 -relx 0.828 -y 0 -rely 0.712 -width 97 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but44 \
        -in $top -x 0 -relx 0.426 -y 0 -rely 0.949 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but45 \
        -in $top -x 0 -relx 0.528 -y 0 -rely 0.949 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top43 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

